-- Create Order_Lines Table
CREATE TABLE ORDER_LINES (
   	ID      		   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_ID           INT,
    LINE_AMOUNT        NUMBER(12, 2),
    CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID)
);