-- Create Orders Table
CREATE TABLE ORDERS (
    ID           	   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REFERENCE          VARCHAR2(200),
    ORDER_DATE         DATE,
    SUPPLIER_ID        INT,
    TOTAL_AMOUNT       NUMBER(12, 2),
    DESCRIPTION        VARCHAR2(500),
    STATUS             VARCHAR2(50),
    CONSTRAINT FK_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID)
);